### ISSUE TITLE
ergo epm installation error ('ergo_epm' has not attribute 'exports')

### ISSUE THREAD

**Issue by lalmeras** [ergonomica/ergonomica#100]
On the first start, ergonomica asks to install ergo_epm. If I accept, and relaunch ergonomica command as it is asked, ergonomica cannot start because of the following error:

```
[ergo: epm]: [Info] No epm store found!
[ergo: epm]: [Info] Initializing package store at /home/lalmeras/.ergo/.epm..
[ergo: epm]: Adding repository 'Ergonomica Main' at 'https://raw.githubusercontent.com/ergonomica/packages/master/MANIFEST' to store...
Traceback (most recent call last):
  File "/home/lalmeras/.virtualenvs/ergonomica/bin/ergonomica", line 7, in <module>
    from ergonomica.ergo import main
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/ergo.py", line 45, in <module>
    from ergonomica.lib.lib import ns
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/lib/lib/__init__.py", line 39, in <module>
    ns.update(module.exports)
AttributeError: module 'ergo_epm' has no attribute 'exports'
```

If I remove `rm -rf ~/.ergo/packages/ergo_epm.py` I can start again ergonomica, but I suppose that ergo_epm is uninstalled.

**Comment by lschumm** [comment]
This has been resolved in package-epm commit [931df61](https://github.com/ergonomica/package-epm/commit/931df61e2e22ace545df86aeca0a414d350b39f4); epm was previously using an older, (deprecated) standard of defining an Ergonomica function.
