### ISSUE TITLE
[Linux] - Requires one to run ergo_setup before first run.

### ISSUE THREAD

**Issue by purukaushik** [ergonomica/ergonomica#31]
Followed the installation instructions posted [here](https://github.com/ergonomica/ergonomica/wiki/Installation#linux) and found that the documentation requires one more step to complete installation on Linux.

Might have to add this in your wiki installation page for linux:

---
Finally, configure `ergonomica` for first time use by:
```
ergo_setup.sh
```
---

btw - Nice project. Snappy suggestions 👍

**Comment by lschumm** [comment]
Fixed. Thanks for the help!
