### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal)

### ISSUE THREAD

**Issue by ResolveWang** [ergonomica/ergonomica#34]
When I press **space**, it will throw error
`$  Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wpm/.linuxbrew/Cellar/ergonomica/1.1.4/bin/lib/prompt_toolkit/intn
    completions = list(buffer.completer.get_completions(document, complete_even)
  File "/home/wpm/.linuxbrew/Cellar/ergonomica/1.1.4/bin/lib/interface/completes
    for result in complete(self.verbs, document.text):
  File "/home/wpm/.linuxbrew/Cellar/ergonomica/1.1.4/bin/lib/interface/completee
    options = [i for i in options if i.startswith(last_word)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal)`

**Comment by codebam** [comment]
I can't reproduce, please specify system details.

**Comment by ResolveWang** [comment]
I use Ubuntu 16.10,here is my os specification

```
[13:06:53] wpm:/home/wpm > cat /proc/version
Linux version 4.8.0-37-generic (buildd@lcy01-17) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017
```

```
[13:08:38] wpm:/home/wpm > uname -a 
Linux wpm 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lschumm** [comment]
Hah, I have nearly the same specs

   $ uname -a
   Linux dijkstra 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

   $ cat /proc/version
   Linux version 4.8.0-37-generic (buildd@lcy01-17) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017

Potentially related to Kylin?

**Comment by ResolveWang** [comment]
Yeah, I think this may be the reason.I use Ubuntu16.10 in docker, it throws no error
