### ISSUE TITLE
ergo - use /bin/sh instead of bash

### ISSUE THREAD

**Issue by Leryan** [ergonomica/ergonomica#37]
Hello,

Is there any need to launch `ergo` from bash? `/bin/bash` isn't a portable path and this make ergonomica to depend on bash.

Using `/bin/sh` is portable and lighter.

**Comment by lschumm** [comment]
Resolved in dfe3598. Thanks!

**Comment by Leryan** [comment]
Well I was speaking about [this one](https://github.com/ergonomica/ergonomica/blob/master/ergo#L1) instead but that's a nice one too :p
