### ISSUE TITLE
Please package this so it can be installed via pip

### ISSUE THREAD

**Issue by panfantastic** [ergonomica/ergonomica#45]
Please could you package/publish this so that it can be installed via pip with the required dependencies.

**Comment by lschumm** [comment]
Getting started on that right now. Thanks for the suggestion!

**Comment by Schtolc** [comment]
All configs for pip package set up. Waiting for owner of ergonomica to build wheel and upload to PyPi.

**Comment by lschumm** [comment]
Done! Live at https://pypi.python.org/pypi/ergonomica.
