### ISSUE TITLE
Suplemon not cross-platform

### ISSUE THREAD

**Issue by OrionBytes** [ergonomica/ergonomica#46]
>No module named '_curses'
after installation

Windows 10 bash - works well after linux way of installation. But the native support will be perfect.

**Comment by OrionBytes** [comment]
Anaconda, Intel Python distribution
https://software.intel.com/en-us/articles/using-intel-distribution-for-python-with-anaconda

Full output:
$ /c/ergonomica/ergonomica
Traceback (most recent call last):
  File "C:/ergonomica/ergonomica.py", line 55, in <module>
    from lib.lang.error_handler import handle_runtime_error
  File "C:\ergonomica\lib\lang\error_handler.py", line 20, in <module>
    from lib.load.load_commands import verbs
  File "C:\ergonomica\lib\load\load_commands.py", line 23, in <module>
    from lib.lib import verbs
  File "C:\ergonomica\lib\lib\__init__.py", line 22, in <module>
    verbs.update(__import__('lib.lib.'+item, globals(), locals(), ['object'], 0).verbs)
  File "C:\ergonomica\lib\lib\edit.py", line 29, in <module>
    from lib.suplemon.cli import main
  File "C:\ergonomica\lib\suplemon\cli.py", line 7, in <module>
    from .main import App, __version__
  File "C:\ergonomica\lib\suplemon\main.py", line 11, in <module>
    from . import ui
  File "C:\ergonomica\lib\suplemon\ui.py", line 10, in <module>
    from .prompt import Prompt, PromptBool, PromptFile
  File "C:\ergonomica\lib\suplemon\prompt.py", line 8, in <module>
    from .editor import Editor
  File "C:\ergonomica\lib\suplemon\editor.py", line 11, in <module>
    from .viewer import Viewer
  File "C:\ergonomica\lib\suplemon\viewer.py", line 9, in <module>
    import curses
  File "C:\Anaconda3\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'

**Comment by lschumm** [comment]
Damn. I chose suplemon to have Windows support but since I don't have a Windows computer, I couldn't test. No such support is planned (https://github.com/richrd/suplemon/issues/101). I'll look into a different (actually cross-platform) editor.

**Comment by OrionBytes** [comment]
How can I help?
I have Windows 10, Windows bash (https://msdn.microsoft.com/en-us/commandline/wsl/about)
mingw, some experience with Python.
And time/will to help such great project :)
But I found it 5 mins ago - so will check the internals.

**Comment by lschumm** [comment]
Thanks for the interest! I was thinking of doing something like https://wiki.wxpython.org/WxHowtoSmallEditor, not entirely sure yet of what editor (if you have any suggestion that would be great). Essentially the `edit` command, who's source is located at lib/lib/edit.py imports `suplemon` in the case that an editor is not set.

**Comment by OrionBytes** [comment]
I'm more from the hardware world (FPGAs, etc.) - so no big experience with console editors and special features for the console applications... I saw that Kaa is multiplatform - https://github.com/kaaedit/kaa
But Python 3.3 or later

**Comment by lschumm** [comment]
> Cygwin environment on Windows platform is not supported at this time, but will be tested after they provide Python 3.3 package.

I'll keep it on my radar but not really having Windows support and less support for *NIX systems (w/o Python3) makes it a no for me.

**Comment by lschumm** [comment]
https://github.com/jonathanslenders/pyvim/ is an option

**Comment by OrionBytes** [comment]
I will check
>Windows support is not that nice. It works, but could be improved. (I think most Windows users are not that interested in this project, but prove me wrong.)

**Comment by lschumm** [comment]
Awesome, I'll get to integration ASAP

**Comment by lschumm** [comment]
Implemented in db7383b! Very beta (doesn't accept files yet: issue #48 ) but basic implementation is there! Thanks @OrionBytes for notifying me that my cross-platform shell was not in fact cross-platform :smiley:!
