### ISSUE TITLE
Add rsync into standard library

### ISSUE THREAD

**Issue by lschumm** [ergonomica/ergonomica#62]
Proposal
========

Integrate the existing rsync-in-python code found here: https://pypi.python.org/pypi/rsync.py in Ergonomica's standard library.

Purpose
-------

In order to make large file operations simple on a variety of platforms (all Ergonomica targets). Additionally, visibility of Ergonomica packages is low, so this would be a good specific selling point for Ergonomica.

Feasability
-----------

**Very feasible**; just drag and drop (with a little formatting).

**Comment by hexdump** [comment]
I don't think we'd be doing any Python interop with the `rsync` command, so I don't really see why I thought this was necessary...
