### ISSUE TITLE
Add pymux for multiplexing

### ISSUE THREAD

**Issue by lschumm** [ergonomica/ergonomica#74]
Proposal
========

Integrate @jonathanslender 's PyMux into base Ergonomica so that any terminal session can be backgrounded/shared.

Purpose
-------

This would allow users to be able to run multiple applications in a single terminal, also allowing multiple "clients" to connect to a single terminal session.

Feasability
-----------

**Somewhat feasible**; would require significant internal Ergonomica redesign.

**Comment by hexdump** [comment]
I would like to keep Ergonomica as just a shell, not a graphical shell environment. I might revive the toolbar functionality (to put information somewhere other than the prompt), but integrating a multiplexer is way too overly complicated in my view.
