### ISSUE TITLE
Add Python2 support

### ISSUE THREAD

**Issue by lalmeras** [ergonomica/ergonomica#99]
With python 2, ergonomica can start but does near to nothing. At prompt, all the commands produce this output: 

```
super() takes at least 1 argument (0 given)
[<current directory>]
```

Ergonomica should either refuse to be installed in python 2 environment or be fixed for python 2 compatibility (I don't notice any statement about python compatibility in the documentation).

Works fine (ls produce a correct output) with a python 3 environment.

(version 2.0.5 installed in virtualenv environment)

**Comment by lschumm** [comment]
Yeah; there doesn't seem to be a great way to limit your installs to a specific version of Python. If the whole point of this shell is _portability_, I should have it support Python 2. Working on that now.

**Comment by lschumm** [comment]
Added Python2 support (at least seems to work on my machine; I'll add unittests soon) in commit adbceba and pushed to PyPI with version 2.0.7.

**Comment by lalmeras** [comment]
Works for me ; I can run ergonomica with python2. Thanks for the fix.

side note: I need to get rid of my `~/.ergo` folder created with ergonomica/python3 as pickle (serialization) is not compatible from python3 to python2 (it failed with `ValueError: unsupported pickle protocol: 3` error).
